In [58]:
import torch

In [59]:
a = torch.tensor([1,2,3], requires_grad=True, dtype=torch.float32)

In [60]:
b = torch.tensor([10, -12, float("nan")], dtype=torch.float32)

In [61]:
c = torch.sum((a - b) ** 2)

In [62]:
c

tensor(nan, grad_fn=<SumBackward0>)

In [63]:
c.backward()

In [64]:
a.grad

tensor([-18.,  28.,  nan])

In [65]:
torch.nn.utils.clip_grad_value_(a, 1)

In [66]:
a.grad

tensor([-1.,  1., nan])

In [67]:
a.grad = torch.nan_to_num(a.grad)

In [68]:
a.grad

tensor([-1.,  1.,  0.])