In [1]:
%load_ext autoreload
%autoreload 2
import torch
import eq
import wandb
from tqdm.notebook import trange
import numpy as np
import warnings
from itertools import product
warnings.filterwarnings('ignore')

In [2]:
device = "cuda"
catalog = eq.catalogs.ANSS_MultiCatalog(mag_completeness=4.5)

Loading existing catalog from /home/zekai/repos/recast/data/ANSS_MultiCatalog.


In [3]:
def train(config=None):
    with wandb.init(config=config):
        config = wandb.config
        try:
            dl_train = catalog.train.get_dataloader(batch_size=config.batch_size)
            dl_val = catalog.val.get_dataloader(batch_size=1)
            dl_test = catalog.test.get_dataloader(batch_size=1)

            model = eq.models.RecurrentTPP(context_size=config.context_size,
                                           num_components=config.num_components,
                                           rnn_type=config.rnn_type,
                                           dropout_proba=config.dropout_proba,
                                           learning_rate=config.lr,
                                           tau_mean=config.tau_mean)
            model = model.to(device)

            epochs = 200
            avg_train_loss_list = []
            avg_val_loss_list = []

            optimizer = torch.optim.AdamW(model.parameters(), 
                                          lr=config.lr, 
                                          betas=config.betas, 
                                          weight_decay=config.weight_decay)
            
            best_model_path = "temp_best_model"
            best_val_loss = float('inf')

            for epoch in trange(epochs):
                running_train_loss = []
                model.train()
                for i, data in enumerate(dl_train):
                    data = data.to(device)
                    optimizer.zero_grad()
                    nll = model.nll_loss(data).mean()
                    nll.backward()
                    optimizer.step()
                    running_train_loss.append(nll.item())
                
                model.eval()
                with torch.no_grad():
                    running_val_loss = []
                    for i, data in enumerate(dl_val):
                        data = data.to(device)
                        nll = model.nll_loss(data).mean()
                        running_val_loss.append(nll.item())

                avg_val_loss = np.mean(running_val_loss)
                avg_train_loss = np.mean(running_train_loss)
                avg_train_loss_list.append(avg_train_loss)
                avg_val_loss_list.append(avg_val_loss)
                wandb.log({"avg_train_loss": avg_train_loss,
                           "avg_val_loss": avg_val_loss,
                           "epoch": epoch})


                if avg_val_loss < best_val_loss:
                    best_val_loss = avg_val_loss
                    torch.save(model.state_dict(), best_model_path)
                

            best_model = eq.models.RecurrentTPP(context_size=config.context_size,
                                                num_components=config.num_components,
                                                rnn_type=config.rnn_type,
                                                dropout_proba=config.dropout_proba,
                                                learning_rate=config.lr)
            best_model.load_state_dict(torch.load(best_model_path))
            best_model = best_model.to(device)
            best_model.eval()
            with torch.no_grad():
                running_test_loss = []
                for i, data in enumerate(dl_test):
                    data = data.to(device)
                    nll = best_model.nll_loss(data).mean()
                    running_test_loss.append(nll.item())
            avg_test_loss = np.mean(running_test_loss)

        except Exception as e:
            print(e)
            avg_test_loss = float("nan")

        wandb.log({"avg_test_loss": avg_test_loss})


In [4]:
import os
os.environ["WANDB_NOTEBOOK_NAME"] = "sweep_updated.ipynb"
wandb.login()

wandb: Currently logged in as: zekai-wang. Use `wandb login --relogin` to force relogin


True

In [5]:
sweep_config = {'method': "random"}
metric = {"name": "avg_test_loss",
          "goal": "minimize"}
sweep_config["metric"] = metric

parameter_dict = {"context_size": {'values': [8, 16, 32, 64, 128]},
                  "num_components": {"values": [8, 16, 32, 64, 128]},
                  "rnn_type": {"value": "LSTM"},
                  "dropout_proba": {"values": [0, 0.1, 0.2, 0.3, 0.4, 0.5]},
                  "lr": {"values": [1e-3, 2e-3, 5e-3, 1e-2, 2e-2, 5e-2]},
                  "betas": {"values": list(product([0.9, 0.99], [0.99, 0.999, 0.9999]))},
                  "weight_decay": {"values": [0, 1e-3, 2e-3, 5e-3, 1e-2, 2e-2, 5e-2]},
                  "batch_size": {"values": [8, 16, 32, 64, 128]},
                  "tau_mean": {"values": [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1.0]}}

sweep_config["parameters"] = parameter_dict

In [6]:
sweep_id = wandb.sweep(sweep_config, project="RecurrentTPP on ANSS Nov 6")

Create sweep with ID: odgh4jcm
Sweep URL: https://wandb.ai/zekai-wang/RecurrentTPP%20on%20ANSS%20Nov%206/sweeps/odgh4jcm


In [7]:
wandb.agent(sweep_id, function=train, count=200)

wandb: Agent Starting Run: 85ed9gsd with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: ghdivi06 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: emuysfra with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: w9f569b4 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.001
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: mx21uywi with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.05
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (1, 2329, 128)) of distribution Weibull(scale: torch.Size([1, 2329, 128]), shape: torch.Size([1, 2329, 128])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.3503, 1.1123, 0.5038,  ..., 1.1671, 2.1863, 1.3151],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]]],
       device='cuda:0')


wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 8kup7x8l with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 604d7d7k with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 1gpbklwg with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 02nh5lpa with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.002
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: svs8i5rg with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: pa46i283 with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: f8vucim9 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.001
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: kzjwrmyx with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 93hk7kxu with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: uoesnjhc with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 8qleii6x with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: w0ukeiu8 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: jzv5bwrg with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 50mfvdcm with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.001
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: jchh608q with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 6bs3g7po with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: z14ibpqd with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: ysyrm7zr with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.05
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 1a0jv7an with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: etwlub1v with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 1539, 128)) of distribution Weibull(scale: torch.Size([16, 1539, 128]), shape: torch.Size([16, 1539, 128])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[ 6.8737,  0.1452, 13.6023,  ...,  1.5941,  3.8222,  0.8020],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         ...,
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],

        [[ 6.8737,  0.1452, 13.6023,  ...,  1.5941,  3.8222,  0.8020],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         ...,
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     

wandb: Agent Starting Run: 9vuroixh with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xxwa4rap with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 9jx3zkic with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 177quqgy with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: i2oszt6s with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xdbq550j with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.01
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: k3zlfis9 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: yza5ljrk with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: bznebl92 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.002
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 676obiyg with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: soxjfi6a with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 10u2tiaz with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: d3qducz0 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: cxmofqyn with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.005
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: j53dmpyh with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 498, 32)) of distribution Weibull(scale: torch.Size([8, 498, 32]), shape: torch.Size([8, 498, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[1.1416, 1.1636, 1.0642,  ..., 1.4332, 1.0723, 0.9171],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[1.1416, 1.1636, 1.0642,  ..., 1.4332, 1.0723, 0.9171],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Agent Starting Run: 1gy0k2f3 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.001
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 2oqiaa4l with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: zkxrz76h with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: tj9in4yg with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: ds5sqzlr with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: ykal3029 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: hr1lnnvn with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: acc0rvgg with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xom79cor with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: gm0so7wl with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: kacequze with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: iigcn379 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: qnqhmnio with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.05
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 5zhjv2xj with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: plum60a9 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.05
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (64, 1076, 64)) of distribution Weibull(scale: torch.Size([64, 1076, 64]), shape: torch.Size([64, 1076, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.3005, 0.3074, 0.8676,  ..., 0.8147, 0.6586, 3.7891],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.3005, 0.3074, 0.8676,  ..., 0.8147, 0.6586, 3.7891],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: fzwn1lqz with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xa8xo8kj with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 2851, 32)) of distribution Weibull(scale: torch.Size([8, 2851, 32]), shape: torch.Size([8, 2851, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[3.3527, 0.8307, 0.8063,  ..., 0.2336, 0.4745, 4.1115],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[3.3527, 0.8307, 0.8063,  ..., 0.2336, 0.4745, 4.1115],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: rhleq575 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: q6t8v9za with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xtc49a76 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.005
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 9o8bjffu with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xdz5iqii with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (1, 2329, 32)) of distribution Weibull(scale: torch.Size([1, 2329, 32]), shape: torch.Size([1, 2329, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[ 2.2675,  3.6793,  3.1626,  ...,  0.8176, 10.6699,  0.5936],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         ...,
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan]]],
       device='cuda:0')


wandb: Agent Starting Run: x6or5xz6 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xaxhdgau with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.05
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: mqfu2jo0 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: fbb043a5 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: tlhji7o5 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (64, 1076, 8)) of distribution Weibull(scale: torch.Size([64, 1076, 8]), shape: torch.Size([64, 1076, 8])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[    nan,  2.0103,  1.0089,  ...,  0.2130,  0.5530, 10.1431],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         ...,
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],

        [[    nan,  2.0103,  1.0089,  ...,  0.2130,  0.5530, 10.1431],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         ...,
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,  

wandb: Agent Starting Run: qubgdryp with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 79j3wb2l with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 095p60fv with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: kv0dxdea with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 78bqifgn with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 8laj85vp with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (128, 3025, 32)) of distribution Weibull(scale: torch.Size([128, 3025, 32]), shape: torch.Size([128, 3025, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[1.2053, 0.6255, 1.0528,  ..., 0.4612, 1.0553, 0.8271],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[1.2053, 0.6255, 1.0528,  ..., 0.4612, 1.0553, 0.8271],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan, 

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: tleuhtl9 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: y4zr1lry with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 8ljsr1i6 with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.02
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 6z6yxgkt with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.001
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: kbha8cdg with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 03i16r9n with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: g8v1856w with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 7d0iemrk with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: tuicuu1f with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 676, 64)) of distribution Weibull(scale: torch.Size([16, 676, 64]), shape: torch.Size([16, 676, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.3663, 0.5719, 2.5202,  ..., 0.5385, 0.7803, 0.7521],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.3663, 0.5719, 2.5202,  ..., 0.5385, 0.7803, 0.7521],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: ys0oifjy with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 3sdn0q91 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 790azak6 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 4gon7jnk with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 9pykwnu5 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: sufi98it with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0
wandb: 	lr: 0.05
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: sopscrun with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 9hg4zsf3 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 2y05fl3k with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: mfu2nti2 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: uicnlfu7 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: mzsplxb0 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.001
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: kb73o11g with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: hq8gkxav with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: rrklre4w with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: c3y9zd2v with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: f8r6nj50 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 9n5xiapu with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 1539, 32)) of distribution Weibull(scale: torch.Size([16, 1539, 32]), shape: torch.Size([16, 1539, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.4950, 0.6969, 0.7239,  ..., 1.0732, 0.5511, 0.4937],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.4950, 0.6969, 0.7239,  ..., 1.0732, 0.5511, 0.4937],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: 631tmcqp with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: wqiysxu7 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: wgrurn2w with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.001
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: twbl3sdn with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (32, 1539, 16)) of distribution Weibull(scale: torch.Size([32, 1539, 16]), shape: torch.Size([32, 1539, 16])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.7794, 0.8007, 0.6437,  ..., 0.9459, 0.9205, 0.6922],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.7794, 0.8007, 0.6437,  ..., 0.9459, 0.9205, 0.6922],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: rh5mmupr with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: oiy1ks4p with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.02
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: utpcxjyn with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.002
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: y06708ti with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: hnvyea9i with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: nr4hwtd2 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.02
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 8e36q3ew with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: hvnukdzr with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.01
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 676, 128)) of distribution Weibull(scale: torch.Size([8, 676, 128]), shape: torch.Size([8, 676, 128])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.4805, 4.7190, 2.4240,  ..., 5.3375, 0.2755, 1.1754],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.4805, 4.7190, 2.4240,  ..., 5.3375, 0.2755, 1.1754],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: 07w6aa99 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0
wandb: 	lr: 0.02
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 8q6i6lqt with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: uq4oznfn with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: kxb0pl6r with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: a7lal2iv with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 664j99hb with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 2872, 8)) of distribution Weibull(scale: torch.Size([16, 2872, 8]), shape: torch.Size([16, 2872, 8])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.7174, 0.6633, 0.7655,  ..., 0.7083, 0.7459, 0.7195],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.7174, 0.6633, 0.7655,  ..., 0.7083, 0.7459, 0.7195],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: 9jd02b08 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: u2rn4kf7 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.05
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: tkat8j89 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: zd9d4kxa with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 676, 128)) of distribution Weibull(scale: torch.Size([8, 676, 128]), shape: torch.Size([8, 676, 128])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.7452, 1.0888, 1.6148,  ..., 1.1200, 1.3023, 1.0452],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.7452, 1.0888, 1.6148,  ..., 1.1200, 1.3023, 1.0452],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: frb8p0w3 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: a36xgcf9 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: y39dml1u with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.05
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: q2qnmot9 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 1539, 64)) of distribution Weibull(scale: torch.Size([16, 1539, 64]), shape: torch.Size([16, 1539, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.7010, 1.3578, 2.0406,  ..., 0.0631, 0.5274, 1.0015],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.7010, 1.3578, 2.0406,  ..., 0.0631, 0.5274, 1.0015],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: mxsbljyw with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: n18qc51l with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: b3ubg2l1 with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 482xse6c with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.001
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: b3smnx01 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.01
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: bg4qqxbw with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: jz3gpirp with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: k2ltc9v6 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 49os720v with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: fb0ingox with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.01
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: aczhizr3 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: i1z7wwqt with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 18ovn8j6 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: nnc66t3m with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: d9tuk4e9 with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.01
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 0lgp1cnj with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 2fosqn3n with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: sarmwjnr with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: heh7uhf4 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: kk0ho96k with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 91pul1c6 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 3hxmh5md with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: hnnmfstw with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: r06vphjr with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: frccxwmc with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 45c0irwt with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xkiefooi with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: x8bwz7m3 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: qy0zi289 with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 188h0g9p with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: s28kgqdm with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 9btb1rh9 with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: woi5qafo with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: nfn9s3g6 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: vgc03ov3 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: cdbjid2n with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: llwhaahh with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: chsypugj with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: oc8hxnav with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 35jkbxpt with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.002
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: uu0klgm8 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 44xbrzh4 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: q6tmwrlf with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: g340y0qw with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: o5otozks with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 78vuw3qh with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 7y9vw5ft with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.05
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (24, 587, 64)) of distribution Weibull(scale: torch.Size([24, 587, 64]), shape: torch.Size([24, 587, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.5533, 0.4975, 0.5320,  ..., 0.8352, 0.7125, 0.5985],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.5533, 0.4975, 0.5320,  ..., 0.8352, 0.7125, 0.5985],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: mo9cbgba with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: jnafus2u with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: ugozypet with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: dmehu3t8 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 005zs8sa with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: clugd8dq with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: qr3zqeb1 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.01
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: vs0ylwn4 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.001
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: hlkxvgkl with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: wpgft6t3 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: jsceu9rq with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: j9lwnwqa with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 2rq90774 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.99]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: i5jj95wh with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: yn54vae5 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.5
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: jc72tsyy with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: g9s4nvmi with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: qawvguyo with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.9999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: p5d6tfdg with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0
wandb: 	lr: 0.02
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.2
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: ldhofyf5 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: k52glf65 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.01
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 0wy1c6x1 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.01
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 8j3epb5s with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.1
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: o9oz1r2g with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.9999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.001
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.05
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: l05hq69p with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.99, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 1
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: r7iaw1vr with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 2949, 8)) of distribution Weibull(scale: torch.Size([8, 2949, 8]), shape: torch.Size([8, 2949, 8])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.6123, 0.4727, 1.5123,  ..., 0.7554, 1.0979, 0.4845],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.6123, 0.4727, 1.5123,  ..., 0.7554, 1.0979, 0.4845],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: e5a5v549 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.99]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	tau_mean: 0.02
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]