In [10]:
%load_ext autoreload
%autoreload 2
import torch
import eq
import wandb
from tqdm.notebook import trange
import numpy as np
import warnings
warnings.filterwarnings('ignore')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
device = "cuda"
catalog = eq.catalogs.ANSS_MultiCatalog(mag_completeness=4.5)

Loading existing catalog from /home/zekai/repos/recast/data/ANSS_MultiCatalog.


In [12]:
def train(config=None):
    with wandb.init(config=config):
        config = wandb.config
        try:
            dl_train = catalog.train.get_dataloader(batch_size=config.batch_size)
            dl_val = catalog.val.get_dataloader(batch_size=1)
            dl_test = catalog.test.get_dataloader(batch_size=1)

            model = eq.models.RecurrentTPP(context_size=config.context_size,
                                           num_components=config.num_components,
                                           rnn_type=config.rnn_type,
                                           dropout_proba=config.dropout_proba,
                                           learning_rate=config.lr)
            model = model.to(device)

            epochs = 200
            avg_train_loss_list = []
            avg_val_loss_list = []

            optimizer = torch.optim.AdamW(model.parameters(), 
                                          lr=config.lr, 
                                          betas=config.betas, 
                                          weight_decay=config.weight_decay)
            
            best_model_path = "temp_best_model"
            best_val_loss = float('inf')

            for epoch in trange(epochs):
                running_training_loss = []
                model.train()
                for i, data in enumerate(dl_train):
                    data = data.to(device)
                    optimizer.zero_grad()
                    nll = model.nll_loss(data).mean()
                    nll.backward()
                    optimizer.step()
                    running_training_loss.append(nll.item())
                
                model.eval()
                with torch.no_grad():
                    running_val_loss = []
                    for i, data in enumerate(dl_val):
                        data = data.to(device)
                        nll = model.nll_loss(data).mean()
                        running_val_loss.append(nll.item())

                avg_val_loss = np.mean(running_val_loss)

                avg_train_loss_list.append(np.mean(running_training_loss))
                avg_val_loss_list.append(avg_val_loss)

                if avg_val_loss < best_val_loss:
                    best_val_loss = avg_val_loss
                    torch.save(model.state_dict(), best_model_path)

            best_model = eq.models.RecurrentTPP(context_size=config.context_size,
                                                num_components=config.num_components,
                                                rnn_type=config.rnn_type,
                                                dropout_proba=config.dropout_proba,
                                                learning_rate=config.lr)
            best_model.load_state_dict(torch.load(best_model_path))
            best_model = best_model.to(device)
            best_model.eval()
            with torch.no_grad():
                running_test_loss = []
                for i, data in enumerate(dl_test):
                    data = data.to(device)
                    nll = best_model.nll_loss(data).mean()
                    running_test_loss.append(nll.item())
            avg_test_loss = np.mean(running_test_loss)

        except Exception as e:
            print(e)
            avg_test_loss = float("nan")

        wandb.log({"avg_test_loss": avg_test_loss})


In [13]:
import os
os.environ["WANDB_NOTEBOOK_NAME"] = "sweep.ipynb"
wandb.login()

wandb: WARNING Calling wandb.login() after wandb.init() has no effect.


True

In [14]:
sweep_config = {'method': "random"}
metric = {"name": "avg_test_loss",
          "goal": "minimize"}
sweep_config["metric"] = metric

parameter_dict = {"context_size": {'values': [8, 16, 32, 64, 128]},
                  "num_components": {"values": [8, 16, 32, 64, 128]},
                  "rnn_type": {"values": ["RNN", "GRU", "LSTM"]},
                  "dropout_proba": {"values": [0, 0.1, 0.2, 0.3, 0.4, 0.5]},
                  "lr": {"values": [1e-3, 2e-3, 5e-3, 1e-2, 2e-2, 5e-2]},
                  "betas": {"value": (0.9, 0.999)},
                  "weight_decay": {"values": [0, 1e-3, 2e-3, 5e-3, 1e-2, 2e-2, 5e-2]},
                  "batch_size": {"values": [8, 16, 32, 64, 128]}}

sweep_config["parameters"] = parameter_dict

In [15]:
sweep_id = wandb.sweep(sweep_config, project="RecurrentTPP on ANSS Nov 5")

Create sweep with ID: 27ca0onv
Sweep URL: https://wandb.ai/zekai-wang/RecurrentTPP%20on%20ANSS%20Nov%205/sweeps/27ca0onv


In [16]:
wandb.agent(sweep_id, function=train, count=100)

wandb: WARNING Calling wandb.login() after wandb.init() has no effect.


<IPython.core.display.HTML object>


wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)


<IPython.core.display.HTML object>
<IPython.core.display.HTML object>


wandb: Agent Starting Run: tdq51qjk with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0
wandb: 	lr: 0.01
wandb: 	num_components: 128
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

Exception in thread Thread-20 (_run_job):
Traceback (most recent call last):
  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/site-packages/wandb/agents/pyagent.py", line 298, in _run_job
    self._function()
  File "/tmp/ipykernel_15643/1366785928.py", line 2, in train
  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 3120, in __exit__
    self._finish(exit_code=exit_code)
  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1938, in _finish
    hook.call()
  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 464, in _jupyter_teardown
    ipython.display_pub.publish = ipython.display_pub._orig_publish
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ZMQDisplayPublisher' object has no attribute '_orig_publish'

During handling of the above exception, another exception occurred:

Traceback (most recent call la

<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>


wandb: Agent Starting Run: exm3zv6a with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

Exception in thread Exception in thread ChkStopThr:
NetStatThr:
Traceback (most recent call last):
Exception in thread Traceback (most recent call last):
IntMsgThr  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
:
  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
        self.run()self.run()
    
self.run()  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/threading.py", line 975, in run

  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/threading.py", line 975, in run
  File "/home/zekai/miniconda3/envs/eq/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
          File "/home/zekai/miniconda3/envs/eq/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 267, in check_network_status
self._target(*se

wandb: Agent Starting Run: hqe7mqof with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 462, 32)) of distribution Weibull(scale: torch.Size([8, 462, 32]), shape: torch.Size([8, 462, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[   nan, 0.7629, 0.7606,  ..., 0.7818, 0.8243, 0.8388],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[   nan, 0.7629, 0.7606,  ..., 0.7818, 0.8243, 0.8388],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Agent Starting Run: 3f23ig8i with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: mozsxwej with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: u688d0ul with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: j0h7zq2i with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 21wsc8e7 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 582, 8)) of distribution Weibull(scale: torch.Size([8, 582, 8]), shape: torch.Size([8, 582, 8])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.8988, 3.6720, 0.7561,  ..., 1.1632, 8.1114, 2.0297],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.8988, 3.6720, 0.7561,  ..., 1.1632, 8.1114, 2.0297],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    n

wandb: Agent Starting Run: sw1p9aoi with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 767, 16)) of distribution Weibull(scale: torch.Size([8, 767, 16]), shape: torch.Size([8, 767, 16])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.6533, 0.7147, 0.8922,  ..., 0.6525, 0.9216, 0.9456],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.6533, 0.7147, 0.8922,  ..., 0.6525, 0.9216, 0.9456],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Agent Starting Run: e5tlwvam with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 3d69ednq with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: j9ifcthf with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 16
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: y9wv6zrt with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.001
wandb: 	num_components: 64
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 257wzujr with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.001
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 7i8chsrd with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.002
wandb: 	num_components: 16
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: q18o6yyc with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: e8dapfta with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: e2f7bwjk with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 32
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: wbmunmus with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 8g9gzltt with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.01
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: e0qxo8kd with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: magsdlci with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 777, 16)) of distribution Weibull(scale: torch.Size([16, 777, 16]), shape: torch.Size([16, 777, 16])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.4928, 0.7050, 0.7236,  ..., 0.5647, 0.5160, 0.6274],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.4928, 0.7050, 0.7236,  ..., 0.5647, 0.5160, 0.6274],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: q33obwz6 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 285wxp5u with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: a63fxrk7 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: p0z13sye with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.02
wandb: 	num_components: 64
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 909, 64)) of distribution Weibull(scale: torch.Size([8, 909, 64]), shape: torch.Size([8, 909, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.5295, 0.5086, 0.6147,  ..., 0.7090, 0.8108, 0.6590],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.5295, 0.5086, 0.6147,  ..., 0.7090, 0.8108, 0.6590],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Agent Starting Run: 1f6s6pyl with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 2935, 128)) of distribution Weibull(scale: torch.Size([16, 2935, 128]), shape: torch.Size([16, 2935, 128])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[1.3437, 0.5140, 0.4770,  ..., 0.0596, 0.0463, 1.0146],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[1.3437, 0.5140, 0.4770,  ..., 0.0596, 0.0463, 1.0146],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan, 

wandb: Agent Starting Run: 978kaz97 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: ax13ohnn with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.02
wandb: 	num_components: 32
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 1076, 32)) of distribution Weibull(scale: torch.Size([16, 1076, 32]), shape: torch.Size([16, 1076, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[5.7141, 1.5932, 2.4905,  ..., 0.6599, 0.7428, 1.3132],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[5.7141, 1.5932, 2.4905,  ..., 0.6599, 0.7428, 1.3132],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: da1t41ed with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.005
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xd43yx3g with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0
wandb: 	lr: 0.001
wandb: 	num_components: 8
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: hsyf2nip with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: y47dxakf with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 32
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: qqvuf2fq with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: htvq44lb with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0
wandb: 	lr: 0.05
wandb: 	num_components: 64
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 3025, 64)) of distribution Weibull(scale: torch.Size([16, 3025, 64]), shape: torch.Size([16, 3025, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.9346, 0.9200, 0.7018,  ..., 0.5013, 0.9179, 0.1993],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.9346, 0.9200, 0.7018,  ..., 0.5013, 0.9179, 0.1993],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: 4cwbpw6e with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (32, 1539, 16)) of distribution Weibull(scale: torch.Size([32, 1539, 16]), shape: torch.Size([32, 1539, 16])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.7473, 0.7565, 0.5851,  ..., 0.6824, 0.9054, 0.7894],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.7473, 0.7565, 0.5851,  ..., 0.6824, 0.9054, 0.7894],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: h8c9yvez with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (24, 587, 8)) of distribution Weibull(scale: torch.Size([24, 587, 8]), shape: torch.Size([24, 587, 8])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[   nan, 0.6734, 0.7205,  ..., 0.6174, 0.6912, 0.3787],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[   nan, 0.6734, 0.7205,  ..., 0.6174, 0.6912, 0.3787],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Agent Starting Run: qtvne1dj with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: tay9ad36 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: fdhl65z7 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: sb3drlqw with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.02
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 1539, 64)) of distribution Weibull(scale: torch.Size([16, 1539, 64]), shape: torch.Size([16, 1539, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[1.1582, 2.9449, 0.2962,  ..., 0.4086, 0.4235, 0.1571],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[1.1582, 2.9449, 0.2962,  ..., 0.4086, 0.4235, 0.1571],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: wfb0gnkh with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: cmibrula with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0
wandb: 	lr: 0.005
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xbnoikwn with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.05
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (64, 2935, 64)) of distribution Weibull(scale: torch.Size([64, 2935, 64]), shape: torch.Size([64, 2935, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.7034, 0.8726, 0.8387,  ..., 0.7350, 0.6769, 0.8187],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.7034, 0.8726, 0.8387,  ..., 0.7350, 0.6769, 0.8187],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: euw5br61 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: clhwfk4h with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: smkr3n9o with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: ojyvgp68 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: fym91ruh with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.001
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: o6f2rhjm with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: ksnhj8wm with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 32
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: e2bu8q1b with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 32
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 2935, 32)) of distribution Weibull(scale: torch.Size([16, 2935, 32]), shape: torch.Size([16, 2935, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.8626, 0.9293, 0.8911,  ..., 1.3364, 1.3425, 2.0519],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.8626, 0.9293, 0.8911,  ..., 1.3364, 1.3425, 2.0519],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: bwkunbmj with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 01jldty5 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 128
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: d30arbq6 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: cnbop7dm with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0
wandb: 	lr: 0.005
wandb: 	num_components: 128
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 643, 128)) of distribution Weibull(scale: torch.Size([8, 643, 128]), shape: torch.Size([8, 643, 128])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.8074, 0.5551, 0.4743,  ..., 0.7552, 0.6703, 1.6492],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.8074, 0.5551, 0.4743,  ..., 0.7552, 0.6703, 1.6492],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: ezuae5jm with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: yj0x8u64 with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: iq68nn2z with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 4i6g08fg with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 16
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: k8d6jy9q with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.005
wandb: 	num_components: 128
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: o8433rik with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: xdhh77fu with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: w10itsx7 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: ssem0b9q with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: qljupd3g with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 909, 64)) of distribution Weibull(scale: torch.Size([8, 909, 64]), shape: torch.Size([8, 909, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[1.2155, 0.7746, 1.8103,  ..., 2.1707, 1.5183, 0.7188],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[1.2155, 0.7746, 1.8103,  ..., 2.1707, 1.5183, 0.7188],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Agent Starting Run: od2ihz98 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 498, 16)) of distribution Weibull(scale: torch.Size([8, 498, 16]), shape: torch.Size([8, 498, 16])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.8190, 0.6556, 0.5395,  ..., 0.5743, 0.5324, 0.8049],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.8190, 0.6556, 0.5395,  ..., 0.5743, 0.5324, 0.8049],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Agent Starting Run: 9o25i4hs with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: gpnr89i9 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (64, 3025, 32)) of distribution Weibull(scale: torch.Size([64, 3025, 32]), shape: torch.Size([64, 3025, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.7264, 0.1865, 0.9606,  ..., 1.1829, 1.0140, 0.7858],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.7264, 0.1865, 0.9606,  ..., 1.1829, 1.0140, 0.7858],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: scb9rhnz with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: jtnm76hf with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.01
wandb: 	num_components: 32
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: vvp0uoqx with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 851, 16)) of distribution Weibull(scale: torch.Size([16, 851, 16]), shape: torch.Size([16, 851, 16])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[1.0230, 0.9667, 0.9398,  ..., 1.9668, 6.0034, 0.4380],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[1.0230, 0.9667, 0.9398,  ..., 1.9668, 6.0034, 0.4380],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: sh7j8125 with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 32
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 1539, 32)) of distribution Weibull(scale: torch.Size([16, 1539, 32]), shape: torch.Size([16, 1539, 32])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.7011, 0.9131, 0.5155,  ..., 0.5511, 0.3479, 0.8231],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.7011, 0.9131, 0.5155,  ..., 0.5511, 0.3479, 0.8231],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: b6gmi060 with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: fvqsappg with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.01
wandb: 	num_components: 16
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 498, 16)) of distribution Weibull(scale: torch.Size([8, 498, 16]), shape: torch.Size([8, 498, 16])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.6898, 0.8705, 0.6010,  ..., 0.4162, 0.6519, 1.2935],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.6898, 0.8705, 0.6010,  ..., 0.4162, 0.6519, 1.2935],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Agent Starting Run: iqee9up9 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.002
wandb: 	num_components: 32
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: dkb3ha3m with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.001
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: tkb8jh8x with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: g4sl7ptn with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: j1vrthf5 with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.002
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: bllonq5z with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.001
wandb: 	num_components: 8
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.01


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 784mp7dk with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.002
wandb: 	num_components: 64
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: jt9uih09 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.001
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: d4qh81br with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.05
wandb: 	num_components: 64
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (32, 828, 64)) of distribution Weibull(scale: torch.Size([32, 828, 64]), shape: torch.Size([32, 828, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[2.5099, 7.9285, 2.3087,  ..., 2.2299, 1.6062, 2.3115],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[2.5099, 7.9285, 2.3087,  ..., 2.2299, 1.6062, 2.3115],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: 7ngkp9iu with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: ljjgo0sr with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.02
wandb: 	num_components: 16
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (16, 1076, 16)) of distribution Weibull(scale: torch.Size([16, 1076, 16]), shape: torch.Size([16, 1076, 16])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.8850, 0.7245, 1.1577,  ..., 0.7717, 0.3603, 0.6934],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.8850, 0.7245, 1.1577,  ..., 0.7717, 0.3603, 0.6934],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    

wandb: Agent Starting Run: wymuseci with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.001
wandb: 	num_components: 16
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 7w0s7aqd with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (32, 2935, 128)) of distribution Weibull(scale: torch.Size([32, 2935, 128]), shape: torch.Size([32, 2935, 128])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.7005, 2.0533, 0.3462,  ..., 1.6893, 2.1679, 0.4387],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.7005, 2.0533, 0.3462,  ..., 1.6893, 2.1679, 0.4387],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan, 

wandb: Agent Starting Run: qagt2a0r with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.2
wandb: 	lr: 0.002
wandb: 	num_components: 8
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 05a2wrb0 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.005
wandb: 	num_components: 32
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: ulynxvxk with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 16
wandb: 	dropout_proba: 0
wandb: 	lr: 0.02
wandb: 	num_components: 8
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.001


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: qai6jklj with config:
wandb: 	batch_size: 128
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.005


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: fu5mjuao with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.002
wandb: 	num_components: 128
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.05


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: e9xa1txo with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 32
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.02
wandb: 	num_components: 128
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 498, 128)) of distribution Weibull(scale: torch.Size([8, 498, 128]), shape: torch.Size([8, 498, 128])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[1.0279, 0.5652, 0.6934,  ..., 0.4409, 0.2124, 1.2281],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[1.0279, 0.5652, 0.6934,  ..., 0.4409, 0.2124, 1.2281],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan

wandb: Agent Starting Run: 1bb0sd4b with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.01
wandb: 	num_components: 8
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: f66fkv4r with config:
wandb: 	batch_size: 16
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 128
wandb: 	dropout_proba: 0.4
wandb: 	lr: 0.05
wandb: 	num_components: 8
wandb: 	rnn_type: GRU
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: azxhywq8 with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.3
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0.02


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Agent Starting Run: 2xg0c8ml with config:
wandb: 	batch_size: 32
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0.1
wandb: 	lr: 0.05
wandb: 	num_components: 16
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: cy4hg6ln with config:
wandb: 	batch_size: 8
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 64
wandb: 	dropout_proba: 0
wandb: 	lr: 0.01
wandb: 	num_components: 64
wandb: 	rnn_type: RNN
wandb: 	weight_decay: 0


  0%|          | 0/200 [00:00<?, ?it/s]

Expected parameter scale (Tensor of shape (8, 857, 64)) of distribution Weibull(scale: torch.Size([8, 857, 64]), shape: torch.Size([8, 857, 64])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[0.9195, 0.6618, 0.8896,  ..., 0.3535, 0.2973, 0.6411],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan]],

        [[0.9195, 0.6618, 0.8896,  ..., 0.3535, 0.2973, 0.6411],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         ...,
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,    nan,  ...,    nan,    nan,    nan],
         [   nan,    nan,  

wandb: Agent Starting Run: 7882uf3t with config:
wandb: 	batch_size: 64
wandb: 	betas: [0.9, 0.999]
wandb: 	context_size: 8
wandb: 	dropout_proba: 0.5
wandb: 	lr: 0.005
wandb: 	num_components: 8
wandb: 	rnn_type: LSTM
wandb: 	weight_decay: 0.002


  0%|          | 0/200 [00:00<?, ?it/s]